const el=id=>document.getElementById(id), won=v=>Math.round(v).toLocaleString('ko-KR')+'원';
const API='https://lyrpqmgmdhkgkwgsmkfy.supabase.co', KEY='sb_publishable_opmBaGpXQ1k-8GaRTlRoqw_LKlXrf3x';
let db=null,user=null,rows=[],current=null,currentId=null,editId=null,stale=false,busy=false,authMode='login',generation=0,ready=false;
const labels={pending:'고민 중',bought:'구매했어요',held:'구매를 참았어요'};
const node=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n};
function monthKey(date){if(!date)return '';const d=new Date(date);return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit'}).format(d).slice(0,7)}
function previousMonth(m){let [y,n]=m.split('-').map(Number);n--;if(!n){n=12;y--}return y+'-'+String(n).padStart(2,'0')}
function stats(list,m){const considered=list.filter(r=>monthKey(r.created_at)===m),decided=list.filter(r=>r.status!=='pending'&&monthKey(r.decided_at)===m),bought=decided.filter(r=>r.status==='bought'),held=decided.filter(r=>r.status==='held');const safe=bought.filter(r=>r.score>=75).length, risky=bought.filter(r=>r.score<45).length;const score=decided.length>=3?Math.round(100*(held.length+safe+(bought.length-safe-risky)*.5)/decided.length):null;let type='기록을 더 모아봐요';if(score!==null)type=held.length/decided.length>=.6?'절약형':risky/decided.length>=.4?'충동소비 경향형':safe/decided.length>=.6?'계획형':'균형형';return{considered:considered.length,boughtAmount:bought.reduce((a,r)=>a+Number(r.price),0),heldCount:held.length,saved:held.reduce((a,r)=>a+Number(r.price),0),score,type,consideredRows:considered,boughtRows:bought}}
const container=document.createElement('div');container.innerHTML=`
<section class="wrap service-section" id="wishlistSection"><div class="service-top"><div><div class="eyebrow">SAVE IT FOR LATER</div><h2>나의 위시리스트</h2><p>지금 결제하지 않아도 괜찮아요. 나중의 나에게 남겨두세요.</p></div><button type="button" class="secondary" id="refreshRecords">기록 새로고침</button></div><div id="serviceConnection" class="service-state" role="status">계정 연결 확인 중…</div><div class="record-grid" id="wishlistGrid"></div></section>
<section class="workspace" id="reportSection"><div class="wrap"><div class="service-top"><div><div class="eyebrow">SMALL CHOICES, BIG CHANGES</div><h2>나의 소비 리포트</h2><p>기록한 선택만 집계합니다. 기준 시간대: 한국.</p></div><label>조회 월<input type="month" id="reportMonth" class="month-select"></label></div><div class="report-kpis" id="reportKpis"></div><div class="report-layout"><article class="card"><h3>지난달과 비교해요</h3><div id="monthChart"></div><p class="service-note" id="monthComparison"></p></article><article class="card"><h3>나의 소비습관</h3><div id="habitResult"></div></article></div><article class="card" style="margin-top:18px"><h3>어떤 소비를 가장 많이 고민했을까요?</h3><div id="categoryChart"></div></article><details class="method"><summary>리포트와 소비습관 점수 기준</summary><p>고민 횟수는 저장된 상품 기록의 생성 월 기준이며, 재분석은 같은 기록을 갱신합니다. 실제 구매·보류는 마지막 선택 날짜의 월에 집계합니다. 선택을 바꾸면 기존 월 집계도 바뀝니다. 보류 금액은 결제하지 않은 상품 가격의 합계로, 실제 예금이나 저축액이 아닙니다.</p><p>해당 월에 구매·보류 결정이 3건 이상이면 소비습관 점수를 제공합니다. 보류 또는 구매 추천 점수 75점 이상인 구매는 100점, 45~74점 구매는 50점, 44점 이하 구매는 0점으로 평가해 평균합니다. 보류 비중 60% 이상은 절약형, 낮은 추천 점수의 구매가 40% 이상은 충동소비 경향형, 높은 추천 점수의 구매가 60% 이상은 계획형, 나머지는 균형형입니다. 실제 충동성이나 재무 건전성을 진단하는 척도가 아닙니다.</p></details></div></section>
<section class="wrap service-section" id="accountSection"><div class="eyebrow">MY SPACE</div><h2>마이페이지</h2><div class="card account-row"><div><strong id="accountName">비회원으로 둘러보는 중</strong><p class="service-note">내 계정에 저장한 기록은 다른 기기에서도 확인할 수 있어요.</p></div><div><button type="button" class="secondary" id="accountLogin">로그인 · 회원가입</button><button type="button" class="secondary hidden" id="logout">로그아웃</button></div></div><div class="service-top" style="margin-top:28px"><h3>나의 구매 판단 기록</h3><label>상태 필터<select id="historyFilter" class="history-filter"><option value="all">전체</option><option value="pending">고민 중</option><option value="bought">구매</option><option value="held">보류</option></select></label></div><div class="record-grid" id="historyGrid"></div><p class="service-note">저장 정보: 상품명·분야·가격·수입·잔액·사용 빈도·대체품·시급·선택 상태. 기록 삭제 버튼으로 삭제할 수 있어요. 비밀번호는 Supabase Auth에서 관리합니다. 공용 기기에서는 반드시 로그아웃하세요.</p></section>
<dialog class="auth-dialog" id="authDialog" aria-labelledby="authTitle"><button type="button" class="auth-close" id="authClose" aria-label="닫기">×</button><h2 id="authTitle">나의 선택을 모아봐요</h2><p class="service-note">로그인하면 판단 기록과 위시리스트를 저장할 수 있어요.</p><div class="auth-tabs"><button type="button" class="secondary" id="loginTab" aria-pressed="true">로그인</button><button type="button" class="secondary" id="signupTab" aria-pressed="false">회원가입</button></div><form id="authForm"><label for="email">이메일</label><input id="email" type="email" required autocomplete="email"><label for="password">비밀번호</label><input id="password" type="password" required minlength="8" maxlength="72" autocomplete="current-password"><label id="consentWrap" class="hidden" style="font-weight:400"><input id="dataConsent" type="checkbox" style="width:auto"> 계정 인증을 위한 이메일 처리와, 저장 시 구매 판단 정보가 계정에 보관됨을 확인했습니다.</label><button class="primary" id="authSubmit" type="submit">로그인</button></form><button type="button" class="sample-btn" id="resend">가입 확인 메일 다시 받기</button><p class="auth-status" id="authStatus" role="status"></p><p class="service-note">가입 확인 메일을 받은 후 인증을 완료해주세요. 메일이 오지 않으면 스팸함도 확인해주세요.</p></dialog>`;
document.querySelector('main').append(container);
const actionArea=node('div',undefined,'service-actions');actionArea.innerHTML='<button class="secondary" id="saveRecord" type="button">판단 기록 저장</button><button class="secondary" id="saveWish" type="button">♡ 위시리스트에 저장</button><button class="secondary" id="markBought" type="button">구매했어요</button><button class="primary" id="markHeld" type="button">이번에는 안 살래요</button>';el('copyStatus').before(actionArea);const saveMessage=node('p','','status');saveMessage.id='saveMessage';saveMessage.setAttribute('role','status');actionArea.after(saveMessage);
el('reportMonth').value=monthKey(new Date());
function authMessage(e){const t=String(e?.message||e||'');if(/Invalid login/i.test(t))return '이메일 또는 비밀번호가 올바르지 않아요.';if(/Email not confirmed/i.test(t))return '메일함에서 가입 확인을 완료해주세요.';if(/rate|429/i.test(t))return '요청이 많아 잠시 제한되었어요. 잠시 후 다시 시도해주세요.';if(/email.*sending|smtp|not authorized|email_address_not_authorized/i.test(t))return '인증 메일 발송 설정을 확인해야 합니다. 운영자에게 문의해주세요.';if(/fetch|network/i.test(t))return '네트워크 연결을 확인한 후 다시 시도해주세요.';return '처리하지 못했어요. '+t.slice(0,180)}
function openAuth(){el('authStatus').textContent=ready?'':'인증 서비스 연결 중입니다. 잠시 기다려주세요.';el('authDialog').showModal()}
el('authOpen').onclick=openAuth;el('accountLogin').onclick=openAuth;el('authClose').onclick=()=>el('authDialog').close();
function mode(v){authMode=v;el('loginTab').setAttribute('aria-pressed',v==='login');el('signupTab').setAttribute('aria-pressed',v==='signup');el('authSubmit').textContent=v==='login'?'로그인':'회원가입';el('consentWrap').classList.toggle('hidden',v!=='signup');el('dataConsent').required=v==='signup';el('password').autocomplete=v==='signup'?'new-password':'current-password';el('authStatus').textContent=''}
el('loginTab').onclick=()=>mode('login');el('signupTab').onclick=()=>mode('signup');
el('authForm').onsubmit=async e=>{e.preventDefault();if(!db){el('authStatus').textContent='서비스 연결을 확인한 뒤 다시 시도해주세요.';return}const b=el('authSubmit');b.disabled=true;try{const credentials={email:el('email').value.trim(),password:el('password').value};const res=authMode==='signup'?await db.auth.signUp({...credentials,options:{emailRedirectTo:location.origin+location.pathname}}):await db.auth.signInWithPassword(credentials);if(res.error)throw res.error;el('password').value='';if(res.data.session){el('authDialog').close();await sessionChanged(res.data.session)}else el('authStatus').textContent='가입 요청을 접수했어요. 메일함에서 확인 링크를 눌러주세요. 기존 계정이면 로그인해주세요.'}catch(e){el('authStatus').textContent=authMessage(e)}finally{b.disabled=false}};
el('resend').onclick=async()=>{if(!db||!el('email').checkValidity()||!el('email').value){el('authStatus').textContent='이메일을 먼저 입력해주세요.';return}el('resend').disabled=true;try{const {error}=await db.auth.resend({type:'signup',email:el('email').value.trim(),options:{emailRedirectTo:location.origin+location.pathname}});if(error)throw error;el('authStatus').textContent='가입 확인 메일 재발송을 요청했어요.'}catch(e){el('authStatus').textContent=authMessage(e)}finally{el('resend').disabled=false}};
el('logout').onclick=async()=>{if(!db)return;const {error}=await db.auth.signOut();if(error){el('serviceConnection').textContent=authMessage(error);return}await sessionChanged(null)};
async function sessionChanged(session){const next=session?.user||null;if(user?.id===next?.id&&ready)return;generation++;user=next;rows=[];currentId=current?crypto.randomUUID():null;editId=null;paint();if(user)await loadRecords()}
async function loadRecords(){if(!db||!user)return;const uid=user.id,g=++generation;el('serviceConnection').textContent='기록을 불러오는 중…';try{let data=[],start=0;while(true){const res=await db.from('purchase_records').select('*').eq('user_id',uid).order('created_at',{ascending:false}).order('id').range(start,start+499);if(res.error)throw res.error;if(g!==generation||user?.id!==uid)return;data.push(...res.data);if(res.data.length<500)break;start+=500}rows=data;paint()}catch(e){if(g===generation)el('serviceConnection').textContent=authMessage(e)}}
function resultButtons(){['saveRecord','saveWish','markBought','markHeld'].forEach(id=>el(id).disabled=stale||busy||!current)}
window.addEventListener('salka:result',e=>{current={...e.detail};currentId=editId||crypto.randomUUID();editId=null;stale=false;el('saveMessage').textContent='저장할 항목과 선택 상태를 골라주세요. 같은 결과는 한 번만 집계돼요.';resultButtons()});window.addEventListener('salka:stale',()=>{stale=true;resultButtons()});
async function save(kind){if(!current||stale||busy)return;if(!user){el('saveMessage').textContent='로그인 후 저장할 수 있어요. 비회원 분석 결과는 그대로 유지됩니다.';openAuth();return}busy=true;resultButtons();const uid=user.id,id=currentId;try{const existing=rows.find(r=>r.id===id);const record={id,user_id:uid,name:current.name,category:current.category||'기타',price:current.price,income:current.income,balance:current.balance,frequency:current.frequency,alternative:current.alternative,wage:current.wage,status:kind==='bought'?'bought':kind==='held'?'held':existing?.status||'pending',wishlist:kind==='wish'?true:existing?.wishlist||false};const {error}=await db.from('purchase_records').upsert(record,{onConflict:'id'});if(error)throw error;if(user?.id!==uid)return;el('saveMessage').textContent=kind==='held'?`이번 선택으로 ${won(current.price)}을 아꼈어요! 실제 저축액이 아닌 구매를 참은 금액으로 기록됩니다.`:kind==='bought'?'구매로 기록했어요. 리포트의 실제 구매 금액에 반영됩니다.':'내 계정에 저장했어요.';await loadRecords()}catch(e){el('saveMessage').textContent=authMessage(e)}finally{busy=false;resultButtons()}}
el('saveRecord').onclick=()=>save('pending');el('saveWish').onclick=()=>save('wish');el('markBought').onclick=()=>save('bought');el('markHeld').onclick=()=>save('held');
async function modify(row,patch,button){if(!user||busy)return;busy=true;button.disabled=true;const uid=user.id;try{const {error}=patch===null?await db.from('purchase_records').delete().eq('id',row.id).eq('user_id',uid):await db.from('purchase_records').update(patch).eq('id',row.id).eq('user_id',uid);if(error)throw error;await loadRecords();if(patch?.status==='held')el('serviceConnection').textContent=`이번 선택으로 ${won(row.price)}을 아꼈어요! (구매를 참은 금액)`}catch(e){el('serviceConnection').textContent=authMessage(e)}finally{busy=false;button.disabled=false}}
function card(r){const c=node('article',undefined,'record-card');c.append(node('span',r.category+' · '+labels[r.status],'tag'),node('h3',r.name),node('strong',won(r.price)+' · '+r.score+'점'),node('p','기록 '+new Date(r.created_at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'})));const a=node('div',undefined,'record-actions');const add=(text,handler)=>{const b=node('button',text,'secondary');b.type='button';b.onclick=()=>handler(b);a.append(b)};add('다시 분석',()=>{if(r.status!=='pending'&&!confirm('이미 결정한 기록입니다. 재분석 후 저장하면 이 기록의 입력 금액과 점수가 갱신됩니다. 계속할까요?'))return;['price','income','balance','frequency','wage'].forEach(k=>el(k).value=r[k]??'');el('product').value=r.name;el('category').value=r.category;document.querySelector(`[name="alternative"][value="${r.alternative}"]`).checked=true;el('form').dispatchEvent(new Event('input',{bubbles:true}));editId=r.id;el('start').scrollIntoView({behavior:'smooth'});el('product').focus({preventScroll:true})});add(r.wishlist?'위시 해제':'위시 저장',b=>modify(r,{wishlist:!r.wishlist},b));if(r.status!=='bought')add('구매했어요',b=>modify(r,{status:'bought'},b));if(r.status!=='held')add('안 살래요',b=>modify(r,{status:'held'},b));if(r.status!=='pending')add('고민 중으로',b=>modify(r,{status:'pending'},b));add('삭제',b=>{if(confirm('이 기록을 삭제할까요? 리포트에서도 제외됩니다.'))modify(r,null,b)});c.append(a);return c}
function paintList(id,list){el(id).replaceChildren(...(user&&list.length?list.map(card):[node('div',user?'아직 기록이 없어요. 구매 판단 결과를 저장해보세요.':'로그인하면 나만의 기록을 확인할 수 있어요.','empty')]))}
function paint(){el('authOpen').textContent=user?'내 계정':'로그인 · 가입';el('authOpen').onclick=user?()=>el('accountSection').scrollIntoView({behavior:'smooth'}):openAuth;el('accountName').textContent=user?.email||'비회원으로 둘러보는 중';el('accountLogin').classList.toggle('hidden',!!user);el('logout').classList.toggle('hidden',!user);el('serviceConnection').textContent=user?`내 기록 ${rows.length}건 · 본인만 조회할 수 있습니다.`:'비회원 구매 판단은 자유롭게 이용할 수 있어요. 저장하려면 로그인해주세요.';paintList('wishlistGrid',rows.filter(r=>r.wishlist));paintList('historyGrid',rows.filter(r=>el('historyFilter').value==='all'||r.status===el('historyFilter').value));paintReport()}
function drawBar(root,label,value,max,color){const r=node('div',undefined,'bar-row'),head=node('div',undefined,'bar-label');head.append(node('span',label),node('strong',won(value)));const track=node('div',undefined,'bar-track'),fill=node('div',undefined,'bar-fill '+(color||''));fill.style.width=(max?Math.max(0,value/max*100):0)+'%';track.append(fill);r.append(head,track);root.append(r)}
function paintReport(){const m=el('reportMonth').value;if(!/^\d{4}-\d{2}$/.test(m))return;const a=stats(rows,m),b=stats(rows,previousMonth(m));el('reportKpis').replaceChildren(...[['구매 고민',a.considered+'회'],['실제 구매 금액',won(a.boughtAmount)],['구매 보류',a.heldCount+'회'],['구매를 참은 금액',won(a.saved)],['소비습관 점수',a.score===null?'산정 대기':a.score+'점']].map(([k,v])=>{const n=node('div',undefined,'kpi');n.append(node('small',k),node('strong',user?v:'—'));return n}));const chart=el('monthChart');chart.replaceChildren();const max=Math.max(a.boughtAmount,b.boughtAmount,a.saved,b.saved,1);drawBar(chart,'지난달 구매',b.boughtAmount,max);drawBar(chart,'이번 달 구매',a.boughtAmount,max);drawBar(chart,'지난달 보류',b.saved,max,'peach');drawBar(chart,'이번 달 보류',a.saved,max,'peach');el('monthComparison').textContent=`저장한 고민 ${a.considered-b.considered>=0?'+':''}${a.considered-b.considered}회 · 구매 금액 변화 ${a.boughtAmount-b.boughtAmount>=0?'+':''}${won(a.boughtAmount-b.boughtAmount)}. 기록이 없는 달은 0으로 집계됩니다.`;const h=el('habitResult');h.replaceChildren(node('div',user?a.type:'로그인하고 기록을 모아보세요','result-value'),node('div',a.score===null?'—':a.score+' / 100','habit-score'),node('p',a.score===null?'이 달의 구매 또는 보류 기록이 3건 이상이면 참고 점수와 유형을 확인할 수 있어요.':a.type==='충동소비 경향형'?'낮은 추천 점수에서도 구매한 기록이 있어요. 다음 구매는 하루 기다리고 필수 생활비부터 남겨보세요.':a.type==='절약형'?'구매를 미루는 선택을 잘 활용했어요. 꼭 필요한 물건까지 무리하게 참을 필요는 없어요.':'사용 계획과 구매 예산을 함께 살펴보고, 일주일에 한 번 기록을 돌아보세요.','service-note'));const grouped={};a.consideredRows.forEach(r=>grouped[r.category]=(grouped[r.category]||0)+1);const top=Object.entries(grouped).sort((a,b)=>b[1]-a[1]);const buys={};a.boughtRows.forEach(r=>buys[r.category]=(buys[r.category]||0)+Number(r.price));const best=Object.entries(buys).sort((a,b)=>b[1]-a[1])[0];const cc=el('categoryChart');cc.replaceChildren(node('p',top.length?'가장 많이 고민한 분야: '+top[0][0]+' ('+top[0][1]+'회)':'아직 해당 월의 저장 기록이 없어요.','service-note'));top.forEach(([k,v])=>{const n=node('div',undefined,'bar-row');n.append(node('div',k+' · '+v+'회','bar-label'));const t=node('div',undefined,'bar-track'),f=node('div',undefined,'bar-fill');f.style.width=v/top[0][1]*100+'%';t.append(f);n.append(t);cc.append(n)});cc.append(node('p',best?'실제 구매 금액이 가장 큰 분야: '+best[0]+' · '+won(best[1]):'이 달에 구매로 표시한 기록은 없어요.','service-note'))}
el('reportMonth').onchange=paintReport;el('historyFilter').onchange=paint;el('refreshRecords').onclick=()=>user?loadRecords():openAuth();paint();resultButtons();
try{const {createClient}=await import('https://esm.sh/@supabase/supabase-js@2.57.4');db=createClient(API,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});db.auth.onAuthStateChange((_event,session)=>{setTimeout(()=>sessionChanged(session),0)});const {data,error}=await db.auth.getSession();if(error)throw error;await sessionChanged(data.session);ready=true}catch(e){el('serviceConnection').textContent='계정 서비스에 연결할 수 없어요. 인터넷 연결을 확인하고 새로고침해주세요. 비회원 분석은 이용 가능합니다.'}
